### ISSUE TITLE
Shrink node_module size

### ISSUE THREAD

**Issue by stanleyxu2005** [nteract/zmq-prebuilt#59] opened 2016-10-08 06:03 UTC
After installing zmq-prebuilt, the `node_module` directory will be 36MB on my machine. This will be a bit too large for a slow connection for first time downloading. There are a lot of dependencies that might only related for the build process. 

I tried to shrink the package to less than 1.5MB by keeping only `bindings` and `nan` and `zmq-prebuilt/build` (sure including all readme and license files). It works just fine. As I'm not a ZMQ heavy user, I don't know, whether my change will break anything. 

If it is not, I think we can remove irrelevant stuffs in postinstall section.

**Comment by rgbkrk** [comment] 2016-10-08 10:22
Odd. On my machine it takes up 18 MB, 17MB of which is all Windows related.

In order for you to have the fallback build for Windows and electron, the package ships with `libzmq.lib` (for both x64 and Win32). This takes up most of the size.

**Comment by lgeiger** [comment] 2016-10-08 15:02
@stanleyxu2005 If you clone it from git and run `npm install` inside the package directory the development dependencies will be installed as well. To only install what's necessary do `npm install --only=production`.

If you install from npm with `npm install zmq-prebuilt` or as a dependency in your `package.json` file, only the necessary stuff will be installed.

**Comment by rgbkrk** [comment] 2016-10-08 15:06
@lgeiger in production mode, we do end up with more than we want since it includes the windows `.lib`s for x64 and Win32. Necessity for building on Windows, yet could be cleaned out `postinstall`.

**Comment by stanleyxu2005** [comment] 2016-10-08 15:10
Nodejs is great but managing thousands of node modules are nightmare. Not all developers have the sense (or a good reason) to exclude irrelevant stuff from npm package. I always try to convince developer to remove irrelevant stuffs in github repo, as `package.json` allows to specify the file list for npm publish.

**Comment by rgbkrk** [comment] 2016-10-08 15:11
You're welcome to make PRs if you know what to do.

**Comment by lgeiger** [comment] 2016-10-08 15:12
@rgbkrk Removing the `.lib` files would break the fallback for building from source. It wouldn't allow the user to upgrade the electron version afterwords.

We could think about hosting the `.lib` files somewhere and only download the one for the right architecture.

I think @stanleyxu2005 was primarily talking about the `node_modules` folder.

**Comment by stanleyxu2005** [comment] 2016-10-09 03:26
@rgbkrk I'm glad to propose PR, if I know how your team test zmq. Is there a good test suite with good test coverage?

**Comment by lgeiger** [comment] 2016-10-09 07:54
@stanleyxu2005 You can run the testsuite with `npm test`.

**Comment by rgbkrk** [comment] 2016-10-09 08:07
We have:

* [Automated tests run on OS X and Linux via Travis](https://travis-ci.org/nteract/zmq-prebuilt)
* [Automated tests run on Windows via AppVeyor](https://ci.appveyor.com/project/nteract/zmq-prebuilt)
* [Automated testing of prebuilts on OS X and Linux via Travis](https://travis-ci.org/nteract/zmq-prebuilt-testing)
* [Automated testing of prebuilts on Windows via AppVeyor](https://ci.appveyor.com/project/nteract/zmq-prebuilt-testing)

It's all the tests from upstream [zeromq.node](https://github.com/JustinTulloss/zeromq.node), and we keep contributing more from here to there.

**Comment by stanleyxu2005** [comment] 2016-10-12 08:35
I tried with `npm run test` all tests passed. But when I run `npm run test:electron`, it will show error as follows. 

![123](https://cloud.githubusercontent.com/assets/5162687/19303048/a4d26b9c-9099-11e6-940d-dcc76a389c1a.png)

**Comment by lgeiger** [comment] 2016-10-12 08:41
Does the file `D:\ij\zmq\zmq-prebuilt\projects\zmq-prebuilt\build\Release\zmq.node` exist?

**Comment by stanleyxu2005** [comment] 2016-10-12 08:47
Sure. I can test everything with `npm run test`.

**Comment by lgeiger** [comment] 2016-10-12 09:01
This is strange. There are two similar issues on the [`bindings`](https://github.com/TooTallNate/node-bindings) package: [#21](https://github.com/TooTallNate/node-bindings/issues/21) and [#26](https://github.com/TooTallNate/node-bindings/issues/26)

This should be fixed there. Could it caused by the wrong access rights?
/cc @rgbkrk

**Comment by stanleyxu2005** [comment] 2016-10-12 09:16
I have checked the build log on appvoyge. It;s fine. I dont know whether the problem is the same as binding electron. I built zmq-prebuilt against 1.4.3 header, but when run `electron-mocha` I have not specify any electron header version.

**Comment by lgeiger** [comment] 2016-10-12 09:30
`electron-mocha` uses the electron version on your system (in your case probably 1.4.3) and executes `mocha` tests inside the electron environment. This is why we have to rebuild it for the correct electron version.

**Closed** 2016-10-24 15:42 UTC
